package mydatasource.utility.bigresult;

import java.sql.ResultSet;
import java.sql.SQLException;

import mydatasource.StatementDecorator;

public class BigResultStatementDecorator extends StatementDecorator {

	protected String lastExecuteSql;

	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		ResultSet rs = super.executeQuery(sql);
		BigResultResultSetDecorator rsd = new BigResultResultSetDecorator();
		rsd.setSql(sql);
		rsd.setMyDataSource(myDataSource);
		rsd.setDelegateResultSet(rs);
		rsd.init();
		return rsd;
	}

	@Override
	public boolean execute(String sql) throws SQLException {
		boolean returnValue = super.execute(sql);
		if (returnValue) {
			lastExecuteSql = sql;
		}
		return returnValue;
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys)
			throws SQLException {
		boolean returnValue = super.execute(sql, autoGeneratedKeys);
		if (returnValue) {
			lastExecuteSql = sql;
		}
		return returnValue;
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		boolean returnValue = super.execute(sql, columnIndexes);
		if (returnValue) {
			lastExecuteSql = sql;
		}
		return returnValue;
	}

	@Override
	public boolean execute(String sql, String[] columnNames)
			throws SQLException {
		boolean returnValue = super.execute(sql, columnNames);
		if (returnValue) {
			lastExecuteSql = sql;
		}
		return returnValue;
	}

	@Override
	public ResultSet getResultSet() throws SQLException {
		ResultSet rs = super.getResultSet();
		BigResultResultSetDecorator rsd = new BigResultResultSetDecorator();
		rsd.setSql(lastExecuteSql);
		rsd.setMyDataSource(myDataSource);
		rsd.setDelegateResultSet(rs);
		rsd.init();
		return rsd;
	}

}
